apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_USER: laraveluser
  MYSQL_PASSWORD: laravelpass
  APP_KEY: base64:fXpu0IT7q63uzBnNMkEleZPARUFr4yfhpJilkayxB6w=
